[project]
name = "pflanzentool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.0",
    "plotly>=6.5.2",
    "pydantic>=2.12.5",
    "scipy>=1.16.3",
    "streamlit>=1.52.2",
    "tinydb>=4.8.2",
]
